### ISSUE TITLE
Improvements in Diann docker - Discussion

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms-containers#2]
@TinyMarsh : 

Thanks a lot for your contribution. I made some minor changes to be compatible with BioContainers guidelines and previous Biocontainer version 1.8.1. 

- Symbolic link from diann-linux to diann to access the tool directly. 
- Working directory /data/ as other Biocontainers tools. 

I also removed the installed wget and unzip tools. Lets take this issue to continue the discussion now that we are more than one.

**Comment by TinyMarsh** [comment]
It looks like you managed to get the image size down to 675MB. Out of interest, what was the main contributor to that size reduction?

**Comment by ypriverol** [comment]
This command add a lot of space: `RUN chmod -R 775 /diann-1.9.2`
Additionally, I added this:  `--no-install-recommends`
